/** All user-facing text (CLAUDE.md: one translation file). */
export const he = {
  appName: 'Finance OS',

  nav: {
    home: 'בית',
    transactions: 'תנועות',
    add: 'הוספה',
    plan: 'תכנון',
    more: 'עוד',
    mainLabel: 'ניווט ראשי',
  },

  common: {
    back: 'חזרה',
    close: 'סגירה',
    cancel: 'ביטול',
    continue: 'המשך',
    save: 'שמירה',
    delete: 'מחיקה',
    edit: 'עריכה',
    add: 'הוספה',
    undo: 'ביטול',
    all: 'הכול',
    none: 'ללא',
    optional: 'לא חובה',
    never: 'אף פעם',
    deleted: 'נמחק',
    saved: 'נשמר',
    showMore: 'הצג הכול',
    errorGeneric: 'משהו השתבש. נסה שוב.',
  },

  context: {
    personal: 'אישי',
    business: 'עסקי',
    both: 'שניהם',
    all: 'הכול',
  },

  kind: {
    income: 'הכנסה',
    expense: 'הוצאה',
    refund: 'זיכוי',
    transfer: 'העברה',
    card_payment: 'חיוב כרטיס',
    opening_balance: 'יתרת פתיחה',
    adjustment: 'תיקון יתרה',
    loan_disbursement: 'קבלת הלוואה',
    loan_payment: 'תשלום הלוואה',
    lending_out: 'הלוואה שנתתי',
    lending_repayment: 'החזר הלוואה',
    investment_trade: 'עסקת ניירות ערך',
  },

  direction: {
    in: 'פלוס (+)',
    out: 'מינוס (−)',
  },

  status: {
    cleared: 'בוצע',
    pending: 'ממתין',
  },

  paymentMethod: {
    card: 'כרטיס',
    bank: 'העברה בנקאית',
    cash: 'מזומן',
    bit: 'ביט',
    paybox: 'פייבוקס',
    pepper: 'פפר פיי',
    check: "צ'ק",
    standing_order: 'הוראת קבע',
    other: 'אחר',
  },

  accountKind: {
    bank: 'בנק',
    cash: 'מזומן',
    savings: 'חיסכון',
    deposit: 'פיקדון',
    brokerage: 'חשבון מסחר',
    prepaid: 'כרטיס נטען',
    platform: 'פלטפורמה',
  },

  /** SPEC 7.3 groups on the accounts screen. */
  accountGroups: {
    bank: 'בנק',
    savings: 'חיסכון ופיקדונות',
    cash: 'מזומן',
    brokerage: 'מסחר',
    other: 'נטען ופלטפורמות',
  },

  home: {
    netWorth: 'שווי נטו',
    netWorthPending: 'יחושב אחרי שתוסיף חשבונות',
    netWorthPartial: '',
    liquid: 'כסף בחשבונות',
    nwDetails: 'פירוט',
    nwIncludesPension: (amount: string) => `כולל ${amount} בפנסיה וחיסכון ארוך טווח`,
    nw: {
      title: 'ממה מורכב השווי הנטו',
      explain: 'כל מה שיש לך, פחות כל מה שאתה חייב. מסגרת אשראי ומסגרת עו"ש הן לא כסף שלך ולא נספרות.',
      assets: 'נכסים',
      liabilities: 'התחייבויות',
      accounts: 'יתרות בחשבונות',
      securities: 'ניירות ערך (שווי שוק)',
      pensionLiquid: 'גמל להשקעה (נזיל)',
      pensionLocked: 'פנסיה וחיסכון ארוך טווח (לא נזיל)',
      lending: 'כסף שהלווית לאחרים',
      negativeAccounts: 'חשבונות ביתרת חובה',
      cards: 'כרטיסי אשראי (חיובים ותשלומים עתידיים)',
      loans: 'יתרת הלוואות',
      checks: "צ'קים שנתת ועוד לא נפרעו",
      debts: 'חובות',
      total: 'שווי נטו',
      liquid: 'נכסים נזילים (אפשר למשוך היום)',
      withoutPension: 'שווי נטו בלי פנסיה',
    },
    budget: 'תקציב החודש',
    cashflow: 'תזרים החודש',
    debts: 'חובות',
    noData: 'אין נתונים',
    emptyTitle: 'מתחילים כאן',
    emptyBody: 'הוסף את החשבון הראשון שלך, עם היתרה שיש בו היום.',
    addAccount: 'הוספת חשבון',
    recent: 'תנועות אחרונות',
    noRecent: 'עוד אין תנועות. לחץ על ➕ כדי להוסיף.',
    topCategories: 'קטגוריות החודש',
    accounts: 'חשבונות',
    cards: 'כרטיסי אשראי',
    uncategorized: 'ללא קטגוריה',
    budgetUsed: (used: string, left: string) => `${used} · נותר ${left}`,
    renewSoon: 'מנויים ותזכורות',
    pendingBanner: (n: number) => `${n} תנועות ממתינות לאישור`,
    wishes: 'Wish List',
    investments: 'השקעות',
    changeFromLastMonth: (s: string) => `${s} מהחודש שעבר`,
    debtsHint: 'לחודש',
  },

  /** Dashboard sections under the four metrics (owner request 01/10/2026). */
  dash: {
    insights: 'תובנות',
    swipe: 'החלק לעוד',
    tabs: { month: 'החודש', assets: 'נכסים', future: 'עתיד', business: 'עסק' },
    tabsLabel: 'תצוגת הדשבורד',
    incomeVsExpense: 'הכנסות מול הוצאות',
    sixMonths: '6 חודשים',
    income: 'הכנסות',
    expense: 'הוצאות',
    dailySpending: 'הוצאה יומית החודש',
    dailyAverage: (avg: string) => `ממוצע ליום ${avg}`,
    whereMoneyWent: 'לאן הלך הכסף',
    vsLastMonth: 'מול אותם ימים בחודש שעבר',
    newThisMonth: 'חדש',
    topPayees: 'בתי עסק מובילים',
    times: (n: number) => `${n}×`,
    budgetByCategory: 'תקציב לפי קטגוריה',
    netWorth12: 'שווי נטו, 12 חודשים',
    allocation: 'פיזור הנכסים',
    allocationKeys: { accounts: 'חשבונות', securities: 'ניירות ערך', pensionLiquid: 'גמל להשקעה', pensionLocked: 'פנסיה וחיסכון ארוך טווח', lending: 'הלוואות לאחרים' },
    portfolio: 'תיק ההשקעות',
    pension: 'פנסיה וחיסכון',
    depositsYtd: (s: string) => `הפקדות מתחילת השנה ${s}`,
    forecast: 'יתרה צפויה, 30 יום',
    lowPoint: (amount: string, date: string) => `נקודה נמוכה: ${amount} ב-${date}`,
    upcoming: 'חיובים והכנסות קרובים',
    noUpcoming: 'אין חיובים צפויים ב-30 הימים הקרובים.',
    empty: 'עוד אין מספיק נתונים לגרף הזה.',
    insight: {
      forecast_low: (account: string, date: string, amount: string) => `${account} צפוי לרדת ל-${amount} ב-${date}`,
      card_charge: (card: string, date: string) => `${card} יחויב ב-${date}`,
      card_covered: 'יש מספיק בחשבון החיוב',
      card_not_covered: 'אין מספיק בחשבון החיוב',
      vat_due: (date: string) => `מע"מ לתשלום עד ${date}`,
      budget_over: (cat: string, pct: string) => `${cat}: ${pct} מהתקציב`,
      above_usual: (cat: string, pct: string) => `${cat}: ${pct} מעל הרגיל`,
      above_usual_body: (cur: string, avg: string) => `${cur} החודש, ממוצע 3 חודשים ${avg}`,
      renewal: (name: string, what: string, date: string) => `${name}: ${what} ב-${date}`,
      savings_good: (pct: string) => `חסכתם ${pct} מההכנסה בחודש שעבר`,
      savings_bad: (pct: string) => `הוצאתם ${pct} יותר מההכנסה בחודש שעבר`,
    },
  },

  banners: {
    installTitle: 'התקנה למסך הבית',
    installBodyIos: 'בספארי: כפתור השיתוף ← "הוסף למסך הבית". כך הנתונים שמורים טוב יותר והאפליקציה עובדת בלי רשת.',
    installBodyOther: 'התקן את האפליקציה מתפריט הדפדפן כדי שהנתונים יישמרו טוב יותר.',
    backupTitle: 'הגיע הזמן לגיבוי',
    backupBody: (days: string) => `הגיבוי האחרון: ${days}. הנתונים שמורים רק במכשיר הזה.`,
    backupNever: 'עוד לא גיבית',
    backupAction: 'לגיבוי',
    storageTitle: 'האחסון לא מוגן',
    storageBody: 'הדפדפן עלול למחוק נתונים אם האפליקציה לא תיפתח זמן רב. התקן למסך הבית וגבה באופן קבוע.',
    dismiss: 'סגירה',
    updateTitle: 'גרסה חדשה זמינה',
    updateBody: 'העדכון לא משנה את הנתונים שלך.',
    updateAction: 'עדכון עכשיו',
    offlineReady: 'האפליקציה מוכנה לעבודה בלי רשת',
  },

  quickAdd: {
    title: 'הוספה מהירה',
    expense: 'הוצאה',
    income: 'הכנסה',
    transfer: 'העברה',
    refund: 'זיכוי',
    businessIncome: 'הכנסה עסקית',
    businessExpense: 'הוצאה עסקית',
    payslip: 'תלוש שכר',
    check: "צ'ק",
    adjustment: 'תיקון יתרה',
    account: 'חשבון',
    needAccount: 'כדי להוסיף תנועה צריך קודם חשבון.',
  },

  transactions: {
    title: 'תנועות',
    emptyTitle: 'אין תנועות',
    emptyBody: 'לחץ על ➕ כדי להוסיף את התנועה הראשונה.',
    noResults: 'אין תנועות שמתאימות לחיפוש.',
    search: 'חיפוש',
    searchPlaceholder: 'בית עסק, תיאור, סכום, תגית',
    filters: 'סינון',
    clearFilters: 'ניקוי סינון',
    filterAccount: 'חשבון',
    filterCard: 'כרטיס',
    filterCategory: 'קטגוריה',
    filterTag: 'תגית',
    filterContext: 'אישי / עסקי',
    filterKind: 'סוג',
    filterFrom: 'מתאריך',
    filterTo: 'עד תאריך',
    dayTotal: 'סה"כ ליום',
    pending: 'ממתין',
    newTitle: 'תנועה חדשה',
    editTitle: 'עריכת תנועה',
    deletedToast: 'התנועה נמחקה',
    savedToast: 'התנועה נשמרה',
    count: (n: number) => `${n.toLocaleString('he-IL')} תנועות`,
  },

  txForm: {
    kind: 'סוג',
    moreKinds: 'סוגים נוספים',
    amount: 'סכום',
    amountPlaceholder: '0.00',
    date: 'תאריך',
    account: 'חשבון',
    source: 'חשבון או כרטיס',
    accountsGroup: 'חשבונות',
    cardsGroup: 'כרטיסים',
    fromAccount: 'מחשבון',
    toAccount: 'לחשבון',
    category: 'קטגוריה',
    noCategory: 'ללא קטגוריה',
    payee: 'בית עסק / אדם',
    payeePlaceholder: 'שופרסל, רמי לוי, ועד בית',
    description: 'תיאור',
    note: 'הערה',
    noteRequired: 'הערה (חובה בתיקון)',
    receipts: 'קבלות',
    addReceipt: 'צילום או קובץ',
    removeReceipt: 'הסרה',
    tags: 'תגיות',
    tagsPlaceholder: 'מופרדות ברווח: חופשה אילת',
    context: 'שייך ל',
    paymentMethod: 'אמצעי תשלום',
    status: 'סטטוס',
    direction: 'כיוון',
    suggestion: (name: string) => `הצעה: ${name}`,
    managedBy: (m: string) => `התנועה נוצרה ממסך ${m}. כדי למחוק אותה, מחק שם.`,
    beforeOpening: (d: string) => `שים לב: התאריך לפני יתרת הפתיחה (${d}). יתרת הפתיחה כבר כוללת תנועות מלפני כן, והתנועה תיספר פעמיים.`,
    adjustmentHint: 'תיקון משנה את היתרה בלי להיחשב הכנסה או הוצאה. תעד למה.',
    openingHint: 'יתרת פתיחה אינה הכנסה. אפשר רק אחת לכל חשבון.',
    errors: {
      amount: 'הזן סכום חיובי, עד שתי ספרות אחרי הנקודה.',
      account: 'בחר חשבון.',
      toAccount: 'בחר חשבון יעד שונה מחשבון המקור.',
      note: 'תיקון דורש הערה.',
      direction: 'בחר כיוון.',
      date: 'בחר תאריך.',
      opening_balance_exists: 'לחשבון הזה כבר יש יתרת פתיחה. ערוך אותה במקום להוסיף חדשה.',
    },
  },

  accounts: {
    title: 'חשבונות',
    add: 'חשבון חדש',
    edit: 'עריכת חשבון',
    total: 'סה"כ',
    closed: 'חשבונות סגורים',
    empty: 'עוד אין חשבונות.',
    name: 'שם החשבון',
    namePlaceholder: 'עו"ש לאומי',
    kind: 'סוג',
    institution: 'בנק / גוף',
    noInstitution: 'ללא',
    openingBalance: 'יתרה היום',
    openingBalanceHint: 'הזן את היתרה כפי שהיא בבנק. במינוס? הוסף סימן מינוס.',
    openingDate: 'נכון לתאריך',
    overdraftLimit: 'מסגרת אשראי בעו"ש',
    overdraftRate: 'ריבית שנתית על המינוס (%)',
    visibleOnDashboard: 'להציג בדף הבית',
    closeAccount: 'סגירת חשבון',
    reopenAccount: 'פתיחה מחדש',
    deleteAccount: 'מחיקת חשבון',
    closeNotZero: 'אפשר לסגור חשבון רק כשהיתרה 0. העבר את היתרה או הוסף תיקון.',
    deleteHasTx: 'לחשבון יש תנועות, ולכן אי אפשר למחוק אותו. אפשר לסגור אותו.',
    deleteHasCards: 'יש כרטיסים שמחויבים מהחשבון הזה.',
    balance: 'יתרה',
    overdrawn: 'במינוס',
    availableWithOverdraft: 'זמין כולל מסגרת',
    overdraftAlert: (pct: string) => `ניצלת ${pct} מהמסגרת`,
    monthlyInterest: 'ריבית משוערת לחודש',
    incomeThisMonth: 'הכנסות החודש',
    expenseThisMonth: 'הוצאות החודש',
    balanceChart: 'יתרה ב-90 הימים האחרונים',
    transactions: 'תנועות',
    addTransaction: 'הוספת תנועה',
    kindFilterAll: 'הכול',
  },

  cards: {
    title: 'כרטיסים',
    add: 'כרטיס חדש',
    edit: 'עריכת כרטיס',
    name: 'שם הכרטיס',
    namePlaceholder: 'כאל ויזה זהב',
    issuer: 'חברת כרטיסים',
    last4: '4 ספרות אחרונות',
    last4Hint: 'רק 4 ספרות. מספר כרטיס מלא לא נשמר.',
    kind: 'סוג',
    credit: 'אשראי (חיוב נדחה)',
    debit: 'דביט (חיוב מיידי)',
    billingAccount: 'חשבון לחיוב',
    chargeDay: 'יום החיוב בחודש',
    calendarCycle: 'מחזור לפי חודש קלנדרי',
    calendarCycleHint: 'ברוב הכרטיסים: קניות של כל החודש מחויבות בחודש הבא. אם המחזור נסגר ביום אחר, כבה והזן אותו.',
    cutoffDay: 'יום סגירת המחזור',
    creditLimit: 'מסגרת אשראי',
    closeCard: 'סגירת כרטיס',
    reopenCard: 'הפעלה מחדש',
    deleteCard: 'מחיקת כרטיס',
    deleteHasTx: 'יש תנועות בכרטיס, ולכן אי אפשר למחוק אותו. אפשר לסגור אותו.',
    needAccount: 'כדי להוסיף כרטיס צריך קודם חשבון בנק לחיוב.',
    nextCharge: 'החיוב הקרוב',
    noCharge: 'אין חיוב פתוח',
    chargeOn: (d: string) => `ב-${d}`,
    available: 'מסגרת פנויה',
    utilization: 'ניצול מסגרת',
    openTotal: 'חיובים פתוחים',
    futureInstallments: 'תשלומים עתידיים',
    statements: 'חיובים',
    statementOf: (d: string) => `חיוב ${d}`,
    period: (a: string, b: string) => `${a} עד ${b}`,
    status: { open: 'פתוח', closed: 'נסגר, ממתין לחיוב', paid: 'שולם' },
    carried: 'זיכוי מחיוב קודם',
    installmentOf: (n: number, c: number) => `תשלום ${n} מתוך ${c}`,
    paymentMismatch: (paid: string, total: string) => `הבנק חויב ${paid}, אבל סכום החיוב עכשיו ${total}.`,
    alignPayment: 'עדכון החיוב לסכום',
    futureByMonth: 'תשלומים עתידיים לפי חודש',
    empty: 'אין עדיין חיובים בכרטיס.',
    debitNote: 'כרטיס דביט: כל עסקה יורדת מיד מחשבון הבנק, בלי חיוב חודשי.',
    addPurchase: 'הוספת עסקה',
  },

  installments: {
    toggle: 'בתשלומים?',
    count: 'מספר תשלומים',
    kind: 'סוג',
    installments: 'תשלומים',
    credit: 'קרדיט (עם ריבית)',
    interest: 'סך הריבית',
    interestHint: 'הסכום למעלה צריך לכלול את הריבית. היא מוצגת בנפרד.',
    recognition: 'בתקציב',
    upfront: 'הכול בחודש הקנייה',
    spread: 'לפי חודש חיוב',
    firstCharge: 'חיוב ראשון',
    preview: (first: string, rest: string, n: number) => (n > 1 ? `${first} ואחר כך ${n - 1} × ${rest}` : first),
    countError: 'בין 2 ל-60 תשלומים',
  },

  categories: {
    title: 'קטגוריות',
    add: 'קטגוריה חדשה',
    edit: 'עריכת קטגוריה',
    name: 'שם',
    type: 'סוג',
    typeExpense: 'הוצאה',
    typeIncome: 'הכנסה',
    parent: 'קטגוריית אב',
    noParent: 'ללא (ראשית)',
    context: 'שייך ל',
    includeInBudget: 'נכלל בתקציב',
    monthlyBudget: 'תקציב חודשי',
    expense: 'הוצאות',
    income: 'הכנסות',
    business: 'עסק',
    errors: {
      parent_too_deep: 'אפשר רק רמה אחת של תת-קטגוריות.',
      parent_type: 'תת-קטגוריה חייבת להיות מאותו סוג כמו האב.',
      has_children: 'לקטגוריה הזו יש תת-קטגוריות, ולכן היא לא יכולה להיות תת-קטגוריה.',
      parent_self: 'קטגוריה לא יכולה להיות האב של עצמה.',
    },
    deleteHint: 'תנועות קיימות ישמרו את הקטגוריה בהיסטוריה.',
  },

  plan: {
    title: 'תכנון',
    budget: 'תקציב',
    recurring: 'חשבונות קבועים ומנויים',
    wishList: 'Wish List',
    forecast: 'תחזית יתרה',
  },

  budget: {
    title: 'תקציב',
    prev: 'חודש קודם',
    next: 'חודש הבא',
    total: 'תקציב החודש',
    used: 'נוצל',
    left: 'נותר',
    over: 'חריגה',
    of: (budget: string) => `מתוך ${budget}`,
    noBudget: 'ללא תקציב',
    uncategorized: 'ללא קטגוריה',
    states: { ok: 'תקין', near: 'קרוב לתקרה', over: 'חריגה', none: '' },
    empty: 'אין הוצאות בתקציב בחודש הזה. אפשר להגדיר תקציב לכל קטגוריה.',
    edit: 'תקציב לקטגוריה',
    monthly: 'תקציב חודשי קבוע',
    thisMonth: (m: string) => `רק לחודש ${m}`,
    thisMonthHint: 'השאר ריק כדי להשתמש בתקציב הקבוע.',
    includeRecurring: 'לכלול חשבונות קבועים ומנויים',
    includeRecurringHint: 'ברירת המחדל: לא נכללים, כמו בתבנית (15.5)',
    setBudgets: 'הגדרת תקציבים',
    notInBudget: 'קטגוריות בלי תקציב',
  },

  recurring: {
    title: 'חשבונות קבועים ומנויים',
    add: 'הוספה',
    new: 'פריט חדש',
    edit: 'עריכה',
    monthlyExpenses: 'הוצאות קבועות בחודש',
    monthlyIncome: 'הכנסות קבועות בחודש',
    normalizedHint: 'מנורמל לחודש לפי התדירות',
    next: 'הבא',
    overdue: 'עבר המועד',
    markPaid: 'שולם',
    paidToast: 'נרשם כשולם',
    actualAmount: 'הסכום בפועל',
    pendingTitle: 'ממתינות לאישור',
    pendingHint: 'נוצרו אוטומטית ביום החיוב. אשר או בטל.',
    confirm: 'אישור',
    cancelTx: 'ביטול',
    empty: 'עוד אין חשבונות קבועים. הוסף חשמל, ארנונה, סלולר, מנויים או משכורת.',
    inactive: 'לא פעילים',
    name: 'שם',
    namePlaceholder: 'ארנונה, נטפליקס, משכורת',
    kind: 'סוג',
    kinds: { bill: 'חשבון קבוע', subscription: 'מנוי', income: 'הכנסה קבועה', transfer: 'הוראת קבע' },
    amount: 'סכום',
    amountUsage: 'סכום אחרון (לא חובה)',
    frequency: 'תדירות',
    frequencies: { usage_based: 'לפי שימוש', daily: 'יומי', weekly: 'שבועי', monthly: 'חודשי', bimonthly: 'דו-חודשי', quarterly: 'רבעוני', semiannual: 'חצי שנתי', yearly: 'שנתי' },
    nextDue: 'מועד הבא',
    source: 'משולם מ',
    toAccount: 'לחשבון',
    category: 'קטגוריה',
    status: 'סטטוס',
    statuses: { active: 'פעיל', inactive: 'לא פעיל', grace_period: 'תקופת חסד', trial: 'ניסיון' },
    trialEnd: 'סוף תקופת ניסיון',
    commitmentEnd: 'סוף התחייבות',
    renewal: 'תאריך חידוש',
    autoCreate: 'ליצור תנועה אוטומטית ביום החיוב',
    autoCreateHint: 'התנועה תיווצר כ"ממתינה" עד שתאשר.',
    reminder: 'תזכורת (ימים לפני)',
    cpi: 'צמוד מדד',
    cpiHint: 'להצגה בלבד בגרסה הזו',
    provider: 'ספק',
    note: 'הערה',
    reminders: { due: 'מועד תשלום', trial_end: 'סוף ניסיון', commitment_end: 'סוף התחייבות', renewal: 'חידוש' },
  },

  forecast: {
    title: 'תחזית יתרה',
    account: 'חשבון',
    days: (n: number) => `${n} יום`,
    today: 'היום',
    end: 'בסוף התקופה',
    lowest: 'הנקודה הנמוכה',
    belowZero: (d: string) => `היתרה צפויה לרדת מתחת ל-0 ב-${d}.`,
    belowOverdraft: (d: string) => `היתרה צפויה לעבור את מסגרת האשראי ב-${d}.`,
    events: 'אירועים צפויים',
    noEvents: 'אין אירועים צפויים בתקופה.',
    kinds: { pending: 'ממתין', recurring: 'קבוע', card: 'חיוב כרטיס', loan: 'הלוואה', salary: 'משכורת', check: "צ'ק" },
    upcoming30: 'צפוי ב-30 הימים הקרובים',
    forecastBalance: 'יתרה צפויה',
    noBank: 'הוסף חשבון בנק כדי לראות תחזית.',
  },

  more: {
    title: 'עוד',
    accounts: 'חשבונות וכרטיסים',
    debts: 'הלוואות וחובות',
    checks: "צ'קים",
    investments: 'השקעות',
    pension: 'פנסיה וגמל',
    salary: 'שכר',
    business: 'עסק',
    tax: 'הגדרות מס',
    reports: 'דוחות',
    import: 'ייבוא',
    settings: 'הגדרות',
  },

  importer: {
    title: 'ייבוא קבצים',
    target: 'לאן לייבא',
    file: 'קובץ (CSV, XLS, XLSX)',
    pickFile: 'בחירת קובץ',
    privacy: 'הקובץ נקרא רק במכשיר. שום דבר לא נשלח לשום מקום.',
    readError: 'לא הצלחתי לקרוא את הקובץ. בדוק שהוא CSV, XLS או XLSX.',
    noHeader: 'לא מצאתי שורת כותרות. בחר אותה ידנית.',
    headerRow: 'שורת הכותרות',
    rowN: (n: number) => `שורה ${n}`,
    presetFound: (name: string) => `זוהה מבנה שמור: ${name}`,
    newLayout: 'מבנה חדש. בדוק את שיוך העמודות.',
    mapping: 'שיוך עמודות',
    none: '— לא בשימוש —',
    fields: {
      transactionDate: 'תאריך עסקה',
      chargeDate: 'תאריך חיוב',
      description: 'תיאור / בית עסק',
      chargeAmount: 'סכום חיוב',
      originalAmount: 'סכום עסקה מקורי',
      debit: 'חובה',
      credit: 'זכות',
      signedAmount: 'סכום (עם סימן)',
      installmentNumber: 'מספר תשלום',
      installmentCount: 'מתוך כמה תשלומים',
      note: 'הערות',
      cardLast4: '4 ספרות כרטיס',
    },
    needDate: 'חובה לשייך עמודת תאריך ועמודת סכום.',
    savePreset: 'לשמור את המבנה לפעם הבאה',
    presetName: 'שם המבנה',
    parsed: (n: number, e: number) => `${n} שורות נקראו${e ? `, ${e} שורות לא נקראו` : ''}`,
    toPreview: 'לתצוגה מקדימה',
    previewTitle: 'תצוגה מקדימה',
    summary: { create: 'ייווצרו', duplicate: 'כפילויות', existingPlan: 'תשלומים קיימים', cardPayment: 'חיובי כרטיס', installments: 'עסקאות בתשלומים' },
    flags: {
      import: 'יובא כבר',
      manual: 'כנראה כבר הוזן ידנית',
      cardPayment: (card: string) => `חיוב של ${card}, נוצר אוטומטית`,
      installment: (n: number, c: number) => `תשלום ${n} מתוך ${c}`,
      existingPlan: 'תשלום של עסקה קיימת',
      estimated: 'סכום העסקה משוער',
    },
    include: 'לכלול',
    remember: 'כלל',
    rememberDone: 'נוצר כלל',
    cutoff: (m: number, t: number) => `ב-${m} מתוך ${t} שורות תאריך החיוב בקובץ שונה מהמחושב. אולי יום סגירת המחזור בכרטיס שונה? אפשר לעדכן בהגדרות הכרטיס.`,
    commit: (n: number) => `ייבוא ${n} תנועות`,
    importing: 'מייבא…',
    done: (n: number) => `יובאו ${n} תנועות`,
    viewTransactions: 'לתנועות',
    another: 'ייבוא קובץ נוסף',
    history: 'ייבואים קודמים',
    undo: 'ביטול הייבוא',
    undone: (n: number) => `${n} תנועות הוסרו`,
    undoConfirm: 'למחוק את כל התנועות מהייבוא הזה?',
    back: 'חזרה',
  },

  rules: {
    title: 'כללי קטגוריה',
    hint: 'כללים משייכים קטגוריה לפי תיאור. בייבוא הם חלים אוטומטית, בהזנה ידנית הם הצעה.',
    add: 'כלל חדש',
    edit: 'עריכת כלל',
    match: 'התאמה',
    matches: { contains: 'מכיל', equals: 'שווה בדיוק', regex: 'ביטוי רגולרי' },
    pattern: 'טקסט',
    patternPlaceholder: 'שופרסל',
    category: 'קטגוריה',
    priority: 'עדיפות (גבוה קודם)',
    empty: 'אין עדיין כללים.',
  },

  debts: {
    title: 'הלוואות וחובות',
    taken: 'הלוואות שלקחתי',
    given: 'הלוואות שנתתי',
    addLoan: 'הלוואה חדשה',
    addLending: 'הלוואה שנתתי',
    editLoan: 'עריכת הלוואה',
    editLending: 'עריכה',
    monthlyTotal: 'תשלום חודשי כולל',
    yearlyTotal: 'ב-12 החודשים הקרובים',
    remainingTotal: 'יתרת קרן',
    toCollect: 'לגבייה',
    emptyTaken: 'אין הלוואות פעילות.',
    emptyGiven: 'לא נתת הלוואות.',
    name: 'שם',
    namePlaceholder: 'הלוואה לרכב',
    lenderType: 'מלווה',
    lenderTypes: { bank: 'בנק', card_company: 'חברת כרטיסים', check_discounting: "ניכיון צ'קים", pension_fund: 'הלוואה מקופה', private: 'פרטי', other: 'אחר' },
    principal: 'סכום ההלוואה',
    rateType: 'סוג ריבית',
    rateTypes: { annual: 'שנתית', total: 'סך ריבית לכל התקופה' },
    rate: 'ריבית (%)',
    term: 'מספר חודשים',
    amortization: 'שיטת החזר',
    methods: { spitzer: 'שפיצר (תשלום קבוע)', equal_principal: 'קרן שווה', flat: 'קבוע לפי סך ריבית', bullet: 'הכול בסוף' },
    startDate: 'תאריך קבלה',
    firstPayment: 'תשלום ראשון',
    maturity: 'תאריך פירעון',
    fees: 'עמלות',
    payFrom: 'משלמים מחשבון',
    receivedTo: 'הכסף נכנס לחשבון',
    notReceived: 'לא נכנס לחשבון במעקב',
    totalWithInterest: 'סה"כ כולל ריבית',
    totalInterest: 'סה"כ ריבית',
    paidPrincipal: 'קרן ששולמה',
    paidInterest: 'ריבית ששולמה',
    remaining: 'יתרת קרן',
    next: 'התשלום הבא',
    status: { active: 'פעילה', paid_off: 'נפרעה', overdue: 'בפיגור' },
    recordPayment: 'רישום תשלום',
    paymentAmount: 'סכום ששולם',
    paymentRecorded: 'התשלום נרשם',
    schedule: 'לוח סילוקין',
    scheduleHead: ['#', 'תאריך', 'תשלום', 'ריבית', 'קרן', 'יתרה'],
    paid: 'שולם',
    rateHint: 'ריבית שנתית היא ברירת המחדל (15.1). "סך ריבית" מתאים לתבנית המקורית ומחושב בשיטה הקבועה.',
    borrower: 'למי',
    lendingRate: 'ריבית כוללת (%)',
    lendingDate: 'תאריך',
    fromAccount: 'מחשבון',
    expectedEnd: 'צפי להחזר',
    note: 'הערה',
    totalDue: 'סה"כ להחזר',
    repaid: 'הוחזר',
    recordRepayment: 'רישום החזר',
    repaymentTo: 'לחשבון',
    repaymentRecorded: 'ההחזר נרשם',
    paidOff: 'הוחזר במלואו',
  },

  owed: {
    tab: 'חובות',
    add: 'חוב חדש',
    edit: 'עריכת חוב',
    empty: 'אין חובות. כאן רושמים חוב לחברת החשמל, קנס, חוב במס הכנסה, תיק בהוצאה לפועל או הסדר תשלומים.',
    totalRemaining: 'סה"כ נשאר לשלם',
    monthly: 'תשלום חודשי בהסדרים',
    creditor: 'למי',
    creditorPlaceholder: 'חברת החשמל, עיריית תל אביב, הוצאה לפועל',
    kind: 'סוג',
    kinds: { utility: 'חשבון שלא שולם', fine: 'קנס', tax_authority: 'רשויות המס', collection: 'הוצאה לפועל', legal_settlement: 'הסדר משפטי', personal: 'חוב אישי', other: 'אחר' },
    original: 'סכום החוב',
    date: 'מאז',
    status: 'מצב',
    statuses: { open: 'פתוח', arrangement: 'בהסדר', legal: 'בטיפול משפטי', settled: 'סגור' },
    plan: 'הסדר תשלומים',
    planHint: 'אם הגעת להסדר של סכום קבוע כל חודש.',
    monthlyPayment: 'תשלום חודשי',
    paymentDay: 'יום בחודש',
    planStart: 'מתחיל מ',
    account: 'משלמים מחשבון',
    category: 'קטגוריה (לתזרים)',
    caseNumber: 'מספר תיק (לא חובה)',
    note: 'הערה',
    total: 'סה"כ חוב',
    paid: 'שולם',
    remaining: 'נשאר',
    charges: 'תוספות לחוב',
    addCharge: 'הוספת קנס / ריבית / עמלה',
    chargeKinds: { fine: 'קנס', interest: 'ריבית', fee: 'עמלה', legal: 'הוצאות משפטיות', other: 'אחר' },
    chargeAmount: 'סכום התוספת',
    chargeAdded: 'התוספת נרשמה',
    pay: 'רישום תשלום',
    paymentRecorded: 'התשלום נרשם',
    payments: 'תשלומים',
    next: (d: string) => `התשלום הבא: ${d}`,
    left: (n: number, d: string) => `עוד ${n} תשלומים, עד ${d}`,
    behind: (a: string) => `בפיגור של ${a} בהסדר. כדאי לשלם לפני שנוספות הוצאות.`,
    settled: 'שולם במלואו',
    remove: 'הסרה',
  },

  checks: {
    title: "צ'קים",
    issued: 'נתתי',
    received: 'קיבלתי',
    add: "צ'ק חדש",
    edit: "עריכת צ'ק",
    empty: "אין צ'קים.",
    direction: 'כיוון',
    number: "מספר צ'ק",
    bankName: 'בנק',
    branch: 'סניף',
    amount: 'סכום',
    issueDate: 'תאריך כתיבה',
    dueDate: 'תאריך פירעון',
    counterparty: 'למי / ממי',
    account: 'חשבון',
    category: 'קטגוריה',
    status: 'סטטוס',
    statuses: { pending: 'ממתין', deposited: 'הופקד', cleared: 'נפרע', bounced: 'חזר', cancelled: 'בוטל', discounted: 'נוכה' },
    pendingTotal: 'ממתינים לפירעון',
    postDated: 'דחוי',
    discountLoan: 'הלוואת ניכיון',
    markCleared: 'נפרע',
  },

  wish: {
    title: 'Wish List',
    add: 'פריט חדש',
    edit: 'עריכת פריט',
    empty: 'הרשימה ריקה. הוסף משהו שאתה חוסך אליו.',
    name: 'מה',
    price: 'מחיר',
    category: 'קטגוריה',
    categories: {
      electronics: 'אלקטרוניקה',
      clothing: 'ביגוד ואקססוריז',
      home_garden: 'בית וגינה',
      books_media: 'ספרים ומדיה',
      sports_outdoors: 'ספורט ושטח',
      toys_games: 'צעצועים ומשחקים',
      health_beauty: 'בריאות ויופי',
      automotive: 'רכב',
      appliances: 'מוצרי חשמל',
      food_drink: 'מזון ומשקאות',
      arts_crafts: 'אומנות ויצירה',
      furniture_decor: 'ריהוט ועיצוב',
      musical_instruments: 'כלי נגינה',
      office_supplies: 'ציוד משרדי',
      digital_product: 'מוצר דיגיטלי',
      jewelry_watches: 'תכשיטים ושעונים',
    },
    priority: 'עדיפות',
    priorities: { must: 'חובה', high: 'גבוהה', medium: 'בינונית', low: 'נמוכה' },
    status: 'סטטוס',
    statuses: { active: 'פעיל', inactive: 'לא פעיל', paused: 'מושהה', done: 'הושג' },
    funding: 'מימון',
    fundings: { saving: 'חיסכון', installments: 'תשלומים' },
    startMonth: 'חודש התחלה',
    goalMonth: 'חודש יעד',
    savingsAccount: 'חשבון החיסכון',
    store: 'חנות',
    link: 'קישור',
    image: 'תמונה',
    pickImage: 'בחירת תמונה',
    removeImage: 'הסרת תמונה',
    saved: 'נחסך',
    paidSoFar: 'שולם',
    monthly: 'בחודש',
    monthsLeft: (n: number) => `עוד ${n} חודשים`,
    labels: { done: 'הושג', behind: 'בפיגור', on_track: 'בזמן', no_goal: '' },
    addSaving: 'הפקדה לחיסכון',
    fromAccount: 'מחשבון',
    buy: 'רישום קנייה',
    buyFrom: 'שולם מ',
    savingAdded: 'ההפקדה נרשמה',
    purchaseAdded: 'הקנייה נרשמה',
    needSavings: 'בחר חשבון חיסכון בפריט כדי להפקיד.',
    filterAll: 'הכול',
  },

  invest: {
    title: 'השקעות',
    value: 'שווי תיק',
    cost: 'עלות',
    unrealized: 'רווח/הפסד',
    dividends12m: 'דיבידנד 12 חודשים',
    realizedYtd: 'רווח ממומש השנה',
    estTax: 'מס רווח הון משוער',
    estTaxHint: 'הערכה בלבד: בלי התאמת אינפלציה וקיזוזים בין שנים.',
    sectors: 'סקטורים',
    noSector: 'ללא סקטור',
    positions: 'ניירות',
    addTrade: 'עסקה',
    addSecurity: 'נייר חדש',
    editSecurity: 'עריכת נייר',
    updatePrices: 'עדכון מחירים',
    empty: 'עוד אין השקעות. הוסף נייר ועסקת קנייה.',
    needBrokerage: 'כדי לרשום עסקאות צריך חשבון מסוג "חשבון מסחר".',
    qty: 'כמות',
    avgPrice: 'מחיר ממוצע',
    lastPrice: 'מחיר אחרון',
    noPrice: 'אין מחיר',
    weight: 'משקל',
    yield: 'תשואת דיבידנד',
    yieldOnCost: 'על העלות',
    trades: 'עסקאות',
    symbol: 'סימול',
    name: 'שם',
    exchange: 'בורסה',
    type: 'סוג',
    types: { stock: 'מניה', etf: 'קרן סל', mutual_fund: 'קרן נאמנות', bond: 'אג"ח' },
    sector: 'סקטור',
    priceUnit: 'יחידת מחיר',
    units: { ILS: 'שקלים', ILA: 'אגורות (ת"א)', USD: 'דולר' },
    tradeTitle: 'עסקה חדשה',
    editTrade: 'עריכת עסקה',
    security: 'נייר',
    tradeType: 'סוג עסקה',
    tradeTypes: { buy: 'קנייה', sell: 'מכירה', dividend: 'דיבידנד', fee: 'עמלה', split: 'פיצול', tax: 'מס' },
    account: 'חשבון מסחר',
    pricePerUnit: (u: string) => `מחיר ליחידה (${u})`,
    gross: 'שווי העסקה (₪)',
    grossHint: 'מחושב מהכמות והמחיר. אפשר לתקן לפי אישור הברוקר.',
    fee: 'עמלה (₪)',
    taxWithheld: 'מס שנוכה (₪)',
    fx: 'שער דולר',
    splitHint: 'בפיצול: הכמות היא מספר היחידות שנוספו (מינוס באיחוד).',
    qtyError: 'כמות לא תקינה',
    oversold: 'נמכרו יותר יחידות מהמוחזקות. בדוק את העסקאות.',
    pricesTitle: 'עדכון מחירים',
    pricesHint: 'מחיר ביחידת המחיר של כל נייר. אין חיבור לשרת: עדכון ידני בלבד.',
    usdRate: 'שער דולר-שקל',
    saved: 'המחירים נשמרו',
    date: 'תאריך',
  },

  pension: {
    title: 'פנסיה וגמל',
    total: 'סה"כ צבירה',
    liquid: 'נזיל',
    add: 'קרן חדשה',
    edit: 'עריכת קרן',
    empty: 'עוד אין קרנות. הוסף קרן פנסיה, ביטוח מנהלים, קופת גמל או גמל להשקעה.',
    name: 'שם',
    productType: 'סוג מוצר',
    products: { pension_fund: 'קרן פנסיה', managers_insurance: 'ביטוח מנהלים', provident_fund: 'קופת גמל', investment_provident: 'גמל להשקעה', child_savings: 'חיסכון לכל ילד' },
    provider: 'חברה מנהלת',
    track: 'מסלול',
    policyLast4: '4 ספרות פוליסה',
    feeDeposit: 'דמי ניהול מהפקדה (%)',
    feeBalance: 'דמי ניהול מצבירה (%)',
    source: 'מקור הפקדות',
    sources: { employer: 'מעסיק', self_employed: 'עצמאי', private: 'פרטי' },
    isLiquid: 'נזיל (אפשר למשוך)',
    balance: 'צבירה',
    asOf: (d: string) => `נכון ל-${d}`,
    depositsYtd: 'הפקדות השנה',
    employee: 'עובד',
    employer: 'מעסיק',
    severance: 'פיצויים',
    self: 'עצמאי',
    snapshots: 'דיווחים',
    addSnapshot: 'עדכון יתרה',
    snapshotHint: 'מהדוח הרבעוני, מהמסלקה הפנסיונית או מהר הכסף.',
    date: 'תאריך',
    returnPct: 'תשואה (%)',
    selfDeposit: 'הפקדה עצמאית',
    fromAccount: 'מחשבון',
    deposited: 'ההפקדה נרשמה',
  },

  salary: {
    title: 'שכר',
    employers: 'מעסיקים',
    addEmployer: 'מעסיק חדש',
    editEmployer: 'עריכת מעסיק',
    addPayslip: 'תלוש חדש',
    editPayslip: 'עריכת תלוש',
    empty: 'הוסף מעסיק כדי להזין תלושים.',
    noPayslips: 'עוד אין תלושים.',
    name: 'שם המעסיק',
    vatId: 'ח.פ (לא חובה)',
    startDate: 'תחילת עבודה',
    endDate: 'סיום עבודה',
    payDay: 'יום תשלום בחודש',
    depositAccount: 'חשבון להפקדה',
    pensionFund: 'קרן לפנסיה מהתלוש',
    noFund: 'ללא',
    avg3: 'ממוצע 3 חודשים',
    avg12: 'ממוצע 12 חודשים',
    gross: 'ברוטו',
    net: 'נטו',
    taxRate: 'מס הכנסה אפקטיבי',
    deductionsRate: 'ניכויים מהברוטו',
    month: 'חודש',
    employer: 'מעסיק',
    taxable: 'ברוטו למס (כולל זקיפות)',
    taxableHint: 'ריק = כמו הברוטו',
    incomeTax: 'מס הכנסה',
    ni: 'ביטוח לאומי',
    health: 'מס בריאות',
    pensionEmployee: 'פנסיה עובד',
    pensionEmployer: 'פנסיה מעסיק',
    severance: 'פיצויים',
    other: 'ניכויים אחרים',
    netPay: 'נטו לתשלום',
    components: 'רכיבים (לא חובה)',
    componentKinds: { thirteenth_salary: 'משכורת 13', recreation: 'הבראה', bonus: 'בונוס', overtime: 'שעות נוספות', other: 'אחר' },
    addComponent: 'הוספת רכיב',
    mismatch: (d: string) => `ברוטו פחות ניכויים שונה מהנטו ב-${d}. בדוק את הערכים (אפשר לשמור בכל זאת).`,
    manualNote: 'כל הערכים מוזנים מהתלוש. האפליקציה לא מחשבת מס לשכיר.',
    paidOn: (d: string) => `ייכנס לחשבון ב-${d}`,
    deleteHas: 'יש תלושים למעסיק הזה.',
    needEmployer: 'כדי להזין תלוש, הוסף קודם את המעסיק.',
  },

  tax: {
    title: 'הגדרות מס',
    disclaimer: 'החישובים מבוססים על האחוזים שהזנת. הם כלי תכנון ואינם ייעוץ מס.',
    effective: 'שינוי חל מהיום. הכנסות שכבר נשמרו שומרות את האחוזים שחלו עליהן.',
    vat: 'מע"מ (%)',
    incomeTax: 'מס הכנסה על הרווח העסקי (%)',
    incomeTaxHint: 'לפי רו"ח או לפי המדרגה השולית שלך. חובה לפני מחשבון ההכנסה.',
    ni: 'ביטוח לאומי ומס בריאות (%)',
    niHint: 'האחוז שאתה משלם על הרווח העסקי. חובה לפני מחשבון ההכנסה.',
    niMode: 'ביטוח לאומי',
    niModes: { fixed_monthly: 'סכום קבוע לחודש', percent: 'אחוז מהרווח' },
    niMonthly: 'מקדמת ביטוח לאומי לחודש',
    niMonthlyHint: 'הסכום שיורד כל חודש לפי שובר המקדמות (כולל מס בריאות).',
    basis: 'על מה מחשבים',
    bases: { net_income: 'כל הכנסה לפני מע"מ', profit_ratio: 'לפי יחס הרווח מתחילת השנה' },
    capitalGains: 'מס רווח הון (%)',
    patur: 'תקרת עוסק פטור',
    avgWage: 'שכר ממוצע (לפנסיית חובה)',
    pensionLow: 'פנסיית חובה עד חצי שכר (%)',
    pensionHigh: 'פנסיית חובה מעל חצי שכר (%)',
    vatDueDay: 'יום תשלום המע"מ',
    saved: 'הגדרות המס נשמרו',
    needRates: 'לפני שימוש במחשבון, הזן את אחוז מס ההכנסה ואחוז הביטוח הלאומי שלך.',
  },

  business: {
    title: 'עסק',
    setup: 'הגדרת העסק',
    setupCta: 'הגדרת עסק',
    setupHint: 'מודול העסק מחשב בלבד: מע"מ, הוצאות מוכרות, כמה לשים בצד. אין הפקת חשבוניות.',
    name: 'שם העסק',
    vatStatus: 'סוג עוסק',
    statuses: { exempt: 'עוסק פטור', licensed: 'עוסק מורשה' },
    openDate: 'תאריך פתיחה',
    period: 'דיווח מע"מ',
    periods: { monthly: 'חודשי', bimonthly: 'דו-חודשי' },
    micro: 'עסק זעיר (30% הוצאה קבועה)',
    account: 'חשבון העסק',
    reserveAccount: 'קופת מיסים (לא חובה)',
    none: 'ללא',
    income: 'הכנסה עסקית',
    expense: 'הוצאה עסקית',
    ytd: (y: string) => `מתחילת ${y}`,
    lines: {
      revenue: 'הכנסות (ללא מע"מ)',
      expenses: 'הוצאות מוכרות',
      profit: 'רווח',
      incomeTax: 'מס הכנסה משוער',
      ni: 'ביטוח לאומי משוער',
      reserved: 'הופרש בצד (לפי המחשבון)',
      paid: 'שולם בפועל (מקדמות)',
      gap: 'פער',
    },
    gapHint: 'חיובי = צפוי לתשלום, שלילי = שולם יותר.',
    reserveNote: 'ההפרשה במחשבון מחושבת על כל הכנסה, ולכן היא בדרך כלל גבוהה מהחבות לפי הרווח. ההפרש הוא כסף שהופרש ביתר.',
    unclassified: (n: number) => `${n} הוצאות עסקיות בלי סוג הוצאה לא נספרות. ערוך אותן ובחר סוג.`,
    rateMissing: 'לא הוזן',
    vatTitle: 'מע"מ',
    vatCols: ['תקופה', 'עסקאות', 'תשומות', 'לתשלום'],
    vatPaid: 'שולם',
    vatOpen: 'פתוחה',
    vatRefund: 'להחזר',
    markPaid: 'סימון שולם',
    due: (d: string) => `לתשלום עד ${d}`,
    patur: 'תקרת עוסק פטור',
    turnover: 'מחזור מתחילת השנה',
    projected: 'תחזית שנתית',
    paturAlerts: {
      near: 'הגעת ל-80% מתקרת עוסק פטור.',
      projected_over: 'לפי הקצב הנוכחי תעבור את התקרה השנה.',
      over: 'עברת את תקרת עוסק פטור.',
    },
    paturAdvice: 'כדאי לפנות לרואה חשבון לגבי מעבר לעוסק מורשה.',
    pension: 'פנסיית חובה לעצמאי',
    pensionMonthly: 'חובה משוערת לחודש',
    pensionYtd: 'חובה מתחילת השנה',
    pensionDeposits: 'הפקדות בפועל',
    pensionGap: 'פער',
    pensionNote: 'מעל גיל 60 ובחצי השנה הראשונה מפתיחת העסק אין חובה. מי שגם שכיר מפקיד רק את ההפרש שהמעסיק לא מכסה.',
    setAsideYtd: 'לשים בצד מצטבר',
    incomeThisMonth: 'הכנסות החודש',
    vatThisPeriod: 'מע"מ בתקופה',
    recentIncome: 'הכנסות אחרונות',
    recentExpenses: 'הוצאות אחרונות',
    calcTitle: 'מחשבון הכנסה',
    amount: 'סכום',
    mode: 'הסכום',
    modes: { excl_vat: 'לפני מע"מ', incl_vat: 'כולל מע"מ' },
    date: 'תאריך',
    from: 'ממי',
    toAccount: 'לחשבון',
    status: 'סטטוס',
    received: 'התקבל',
    pending: 'ממתין',
    note: 'הערה',
    breakdown: {
      net: 'לפני מע"מ',
      vat: 'מע"מ',
      total: 'סה"כ',
      base: 'בסיס לחישוב',
      incomeTax: 'מס הכנסה',
      ni: 'ביטוח לאומי',
      vatReserve: 'מע"מ',
      setAside: 'לשים בצד',
      left: 'נשאר לך',
    },
    ratio: (r: string) => `יחס רווח ${r}`,
    niFixed: (a: string) => `ביטוח לאומי: ${a} לחודש (לא מההכנסה)`,
    niFixedLine: (a: string) => `${a} × חודשים`,
    saveIncome: 'שמירת הכנסה',
    savedIncome: 'ההכנסה נשמרה',
    moveReserve: (a: string) => `העבר ${a} לקופת מיסים`,
    moved: 'הועבר לקופת מיסים',
    expenseTitle: 'הוצאה עסקית',
    amountIncl: 'סכום כולל מע"מ',
    vatAmount: 'מע"מ בחשבונית',
    vatAmountHint: 'מחושב אוטומטית. ספק פטור: 0.',
    expenseClass: 'סוג הוצאה',
    invoiceNo: 'מספר חשבונית ספק',
    payFrom: 'שולם מ',
    supplier: 'ספק',
    recognized: 'מוכר במס',
    vatDeductible: 'מע"מ לקיזוז',
  },

  reports: {
    title: 'דוחות',
    kinds: { month: 'חודש', quarter: 'רבעון', year: 'שנה' },
    prev: 'קודם',
    next: 'הבא',
    income: 'הכנסות',
    expense: 'הוצאות',
    net: 'תזרים',
    expenseRatio: 'יחס הוצאות להכנסות',
    savingsRate: 'שיעור חיסכון',
    byCategory: 'הוצאות לפי קטגוריה',
    incomeByCategory: 'הכנסות לפי קטגוריה',
    trend: (y: string) => `הכנסות והוצאות ב-${y}`,
    netWorth: 'שווי נטו לאורך זמן',
    netWorthEmpty: 'הצילום החודשי הראשון ייווצר בתחילת החודש הבא.',
    compare: 'השוואת שנים',
    compareHead: (a: string, b: string) => `${a} מול ${b}`,
    other: 'אחר',
    empty: 'אין תנועות בתקופה הזו.',
    exportCsv: 'ייצוא התקופה ל-CSV',
  },

  institutions: {
    title: 'מוסדות',
    add: 'מוסד חדש',
    edit: 'עריכת מוסד',
    name: 'שם',
    kind: 'סוג',
    kinds: { bank: 'בנק', card_issuer: 'חברת כרטיסים', pension_provider: 'פנסיה וגמל', broker: 'ברוקר', other: 'אחר' },
    code: 'קוד (לא חובה)',
    color: 'צבע',
    logo: 'לוגו',
    logoHint: 'לא חובה. בלי לוגו מוצגת האות הראשונה בצבע המוסד.',
    pickLogo: 'בחירת תמונה',
    removeLogo: 'הסרה',
    ownLogoHint: 'לא חובה. תמונה משלך גוברת על הלוגו של המוסד. בלי תמונה מוצג הלוגו של המוסד או האות הראשונה.',
  },

  prefs: {
    title: 'חישובים',
    budgetRecognition: 'עסקאות בתשלומים בתקציב (ברירת מחדל)',
    costBasis: 'שיטת עלות בניירות ערך',
    costBases: { moving_average: 'ממוצע משוקלל נע', fifo: 'FIFO' },
    forecastDays: 'ימי תחזית',
  },

  demo: {
    title: 'נתוני הדגמה',
    body: 'משפחה אמידה, שנה שלמה אחורה: משכורת ועסק, כרטיסים ותשלומים, השקעות ופנסיה, הלוואות, חובות, צ׳קים, תקציב ו-Wish List. הנתונים שלך נשמרים בצד וחוזרים בלחיצה.',
    load: 'טעינת נתוני הדגמה',
    confirmTitle: 'לטעון נתוני הדגמה?',
    confirmBody: 'הנתונים שלך יישמרו בצד במכשיר, ויחזרו בדיוק כמו שהם כשתלחץ "החזר את הנתונים שלי". ההגדרות, התמה וקוד הנעילה נשארים.',
    confirm: 'טען הדגמה',
    loading: 'טוען…',
    active: 'מצב הדגמה',
    activeBody: 'אתה צופה בנתוני הדגמה. הנתונים שלך שמורים בצד.',
    exit: 'החזר את הנתונים שלי',
    exiting: 'מחזיר…',
    restored: 'הנתונים שלך חזרו',
    blocked: 'לא זמין במצב הדגמה. קודם "החזר את הנתונים שלי".',
    failed: 'הטעינה נכשלה. הנתונים שלך לא השתנו.',
  },

  pin: {
    title: 'קוד נעילה',
    enter: 'הזן קוד',
    wrong: 'קוד שגוי',
    set: 'הגדרת קוד',
    change: 'שינוי קוד',
    remove: 'הסרת קוד',
    newPin: 'קוד חדש (4–6 ספרות)',
    confirmPin: 'אימות הקוד',
    mismatch: 'הקודים לא תואמים',
    invalid: 'הקוד צריך להיות 4 עד 6 ספרות',
    on: 'האפליקציה ננעלת אחרי 5 דקות ברקע',
    off: 'אין קוד',
    hint: 'הגנה מפני מבט מזדמן, לא הצפנה של הנתונים. אם תשכח את הקוד, תצטרך לשחזר מגיבוי.',
    delete: 'מחיקה',
  },

  csv: {
    title: 'ייצוא CSV לרואה חשבון',
    from: 'מתאריך',
    to: 'עד תאריך',
    context: 'תנועות',
    export: 'ייצוא CSV',
    empty: 'אין תנועות בטווח הזה.',
    done: (n: number) => `יוצאו ${n.toLocaleString('he-IL')} תנועות`,
    headers: ['תאריך', 'סוג', 'סכום', 'חשבון', 'כרטיס', 'לחשבון', 'קטגוריה', 'בית עסק', 'תיאור', 'הערה', 'תגיות', 'אישי/עסקי', 'סטטוס', 'מע"מ', 'נטו'],
  },

  settings: {
    title: 'הגדרות',
    appearance: 'תצוגה',
    theme: 'תמה',
    themeSystem: 'לפי המכשיר',
    themeLight: 'בהירה',
    themeDark: 'כהה',
    hideAgorot: 'הסתרת אגורות',
    hideAgorotHint: 'סכומים יוצגו בשקלים שלמים',
    data: 'נתונים',
    categories: 'קטגוריות',
    institutions: 'מוסדות',
    rules: 'כללי קטגוריה',
    import: 'ייבוא קבצים',
    security: 'אבטחה',

    backup: 'גיבוי ושחזור',
    lastBackup: 'גיבוי אחרון',
    backupPassword: 'סיסמה להצפנה (לא חובה)',
    backupPasswordHint: 'בלי סיסמה הקובץ לא מוצפן. אם תשכח את הסיסמה, אי אפשר לשחזר.',
    backupPasswordConfirm: 'אימות סיסמה',
    passwordMismatch: 'הסיסמאות לא תואמות',
    exportBackup: 'ייצוא גיבוי',
    exporting: 'מייצא…',
    exportDone: 'קובץ הגיבוי נשמר',
    restore: 'שחזור מקובץ',
    restoreHint: 'השחזור מחליף את כל הנתונים במכשיר בנתונים מהקובץ.',
    restorePasswordPrompt: 'הקובץ מוצפן. הזן את הסיסמה:',
    restoreCheck: 'בדיקת הקובץ',
    restoreSummary: (date: string, rows: number) => `גיבוי מ-${date}, ${rows.toLocaleString('he-IL')} רשומות.`,
    restoreConfirm1Title: 'להחליף את כל הנתונים?',
    restoreConfirm1Body: 'כל מה ששמור עכשיו במכשיר יימחק ויוחלף בנתונים מהקובץ.',
    restoreConfirm2Title: 'אישור אחרון',
    restoreConfirm2Body: 'אי אפשר לבטל את הפעולה הזו. כדאי לייצא גיבוי של המצב הנוכחי לפני כן.',
    restoreYes: 'כן, להחליף',
    restoreFinal: 'שחזר עכשיו',
    restoreDone: 'השחזור הושלם',
    errors: {
      not_a_backup: 'הקובץ הזה לא גיבוי של Finance OS.',
      newer_version: 'הגיבוי נוצר בגרסה חדשה יותר של האפליקציה. עדכן את האפליקציה ונסה שוב.',
      needs_password: 'הקובץ מוצפן. הזן סיסמה.',
      invalid_data: 'הקובץ פגום או ערוך, ולכן לא שוחזר. הנתונים הקיימים לא השתנו.',
      wrong_password: 'סיסמה שגויה, או שהקובץ פגום.',
      generic: 'משהו השתבש. הנתונים הקיימים לא השתנו.',
    },

    storage: 'אחסון',
    storagePersisted: 'האחסון מוגן מפני מחיקה אוטומטית',
    storageNotPersisted: 'האחסון לא מוגן. התקן למסך הבית.',
    installed: 'מותקן כאפליקציה',
    notInstalled: 'פתוח בדפדפן',

    about: 'אודות',
    privacy: 'כל הנתונים נשמרים במכשיר הזה בלבד. שום נתון לא נשלח לשרת.',
    disclaimer: 'החישובים הם כלי תכנון ואינם ייעוץ מס או ייעוץ פיננסי.',
    version: 'גרסה',
  },
} as const;
