/** All user-facing text (CLAUDE.md: one translation file). */
export const he = {
  appName: 'Finance OS',

  nav: {
    home: 'בית',
    transactions: 'תנועות',
    add: 'הוספה',
    plan: 'תכנון',
    more: 'עוד',
    mainLabel: 'ניווט ראשי',
  },

  common: {
    back: 'חזרה',
    close: 'סגירה',
    cancel: 'ביטול',
    continue: 'המשך',
    save: 'שמירה',
    delete: 'מחיקה',
    edit: 'עריכה',
    add: 'הוספה',
    undo: 'ביטול',
    all: 'הכול',
    none: 'ללא',
    optional: 'לא חובה',
    comingInStage: (n: number) => `בשלב ${n}`,
    comingSoonTitle: 'המסך הזה עוד בבנייה',
    comingSoonBody: (n: number) => `הוא ייבנה בשלב ${n} לפי תוכנית העבודה.`,
    never: 'אף פעם',
    deleted: 'נמחק',
    saved: 'נשמר',
    showMore: 'הצג הכול',
    errorGeneric: 'משהו השתבש. נסה שוב.',
  },

  context: {
    personal: 'אישי',
    business: 'עסקי',
    both: 'שניהם',
    all: 'הכול',
  },

  kind: {
    income: 'הכנסה',
    expense: 'הוצאה',
    refund: 'זיכוי',
    transfer: 'העברה',
    card_payment: 'חיוב כרטיס',
    opening_balance: 'יתרת פתיחה',
    adjustment: 'תיקון יתרה',
    loan_disbursement: 'קבלת הלוואה',
    loan_payment: 'תשלום הלוואה',
    lending_out: 'הלוואה שנתתי',
    lending_repayment: 'החזר הלוואה',
    investment_trade: 'עסקת ניירות ערך',
  },

  direction: {
    in: 'פלוס (+)',
    out: 'מינוס (−)',
  },

  status: {
    cleared: 'בוצע',
    pending: 'ממתין',
  },

  paymentMethod: {
    card: 'כרטיס',
    bank: 'העברה בנקאית',
    cash: 'מזומן',
    bit: 'ביט',
    paybox: 'פייבוקס',
    pepper: 'פפר פיי',
    check: "צ'ק",
    standing_order: 'הוראת קבע',
    other: 'אחר',
  },

  accountKind: {
    bank: 'בנק',
    cash: 'מזומן',
    savings: 'חיסכון',
    deposit: 'פיקדון',
    brokerage: 'חשבון מסחר',
    prepaid: 'כרטיס נטען',
    platform: 'פלטפורמה',
  },

  /** SPEC 7.3 groups on the accounts screen. */
  accountGroups: {
    bank: 'בנק',
    savings: 'חיסכון ופיקדונות',
    cash: 'מזומן',
    brokerage: 'מסחר',
    other: 'נטען ופלטפורמות',
  },

  home: {
    netWorth: 'שווי נטו',
    netWorthPending: 'יחושב אחרי שתוסיף חשבונות',
    netWorthPartial: 'חשבונות וכרטיסים. הלוואות, השקעות ופנסיה יתווספו בהמשך',
    liquid: 'יתרה נזילה',
    budget: 'תקציב החודש',
    cashflow: 'תזרים החודש',
    debts: 'חובות',
    noData: 'אין נתונים',
    emptyTitle: 'מתחילים כאן',
    emptyBody: 'הוסף את החשבון הראשון שלך, עם היתרה שיש בו היום.',
    addAccount: 'הוספת חשבון',
    recent: 'תנועות אחרונות',
    noRecent: 'עוד אין תנועות. לחץ על ➕ כדי להוסיף.',
    topCategories: 'קטגוריות החודש',
    accounts: 'חשבונות',
    cards: 'כרטיסי אשראי',
    uncategorized: 'ללא קטגוריה',
  },

  banners: {
    installTitle: 'התקנה למסך הבית',
    installBodyIos: 'בספארי: כפתור השיתוף ← "הוסף למסך הבית". כך הנתונים שמורים טוב יותר והאפליקציה עובדת בלי רשת.',
    installBodyOther: 'התקן את האפליקציה מתפריט הדפדפן כדי שהנתונים יישמרו טוב יותר.',
    backupTitle: 'הגיע הזמן לגיבוי',
    backupBody: (days: string) => `הגיבוי האחרון: ${days}. הנתונים שמורים רק במכשיר הזה.`,
    backupNever: 'עוד לא גיבית',
    backupAction: 'לגיבוי',
    storageTitle: 'האחסון לא מוגן',
    storageBody: 'הדפדפן עלול למחוק נתונים אם האפליקציה לא תיפתח זמן רב. התקן למסך הבית וגבה באופן קבוע.',
    dismiss: 'סגירה',
  },

  quickAdd: {
    title: 'הוספה מהירה',
    expense: 'הוצאה',
    income: 'הכנסה',
    transfer: 'העברה',
    refund: 'זיכוי',
    adjustment: 'תיקון יתרה',
    account: 'חשבון',
    needAccount: 'כדי להוסיף תנועה צריך קודם חשבון.',
  },

  transactions: {
    title: 'תנועות',
    emptyTitle: 'אין תנועות',
    emptyBody: 'לחץ על ➕ כדי להוסיף את התנועה הראשונה.',
    noResults: 'אין תנועות שמתאימות לחיפוש.',
    search: 'חיפוש',
    searchPlaceholder: 'בית עסק, תיאור, סכום, תגית',
    filters: 'סינון',
    clearFilters: 'ניקוי סינון',
    filterAccount: 'חשבון',
    filterCard: 'כרטיס',
    filterCategory: 'קטגוריה',
    filterTag: 'תגית',
    filterContext: 'אישי / עסקי',
    filterKind: 'סוג',
    filterFrom: 'מתאריך',
    filterTo: 'עד תאריך',
    dayTotal: 'סה"כ ליום',
    pending: 'ממתין',
    newTitle: 'תנועה חדשה',
    editTitle: 'עריכת תנועה',
    deletedToast: 'התנועה נמחקה',
    savedToast: 'התנועה נשמרה',
    count: (n: number) => `${n.toLocaleString('he-IL')} תנועות`,
  },

  txForm: {
    kind: 'סוג',
    moreKinds: 'סוגים נוספים',
    amount: 'סכום',
    amountPlaceholder: '0.00',
    date: 'תאריך',
    account: 'חשבון',
    source: 'חשבון או כרטיס',
    accountsGroup: 'חשבונות',
    cardsGroup: 'כרטיסים',
    fromAccount: 'מחשבון',
    toAccount: 'לחשבון',
    category: 'קטגוריה',
    noCategory: 'ללא קטגוריה',
    payee: 'בית עסק / אדם',
    payeePlaceholder: 'שופרסל, רמי לוי, ועד בית',
    description: 'תיאור',
    note: 'הערה',
    noteRequired: 'הערה (חובה בתיקון)',
    tags: 'תגיות',
    tagsPlaceholder: 'מופרדות ברווח: חופשה אילת',
    context: 'שייך ל',
    paymentMethod: 'אמצעי תשלום',
    status: 'סטטוס',
    direction: 'כיוון',
    suggestion: (name: string) => `הצעה: ${name}`,
    beforeOpening: (d: string) => `שים לב: התאריך לפני יתרת הפתיחה (${d}). יתרת הפתיחה כבר כוללת תנועות מלפני כן, והתנועה תיספר פעמיים.`,
    adjustmentHint: 'תיקון משנה את היתרה בלי להיחשב הכנסה או הוצאה. תעד למה.',
    openingHint: 'יתרת פתיחה אינה הכנסה. אפשר רק אחת לכל חשבון.',
    errors: {
      amount: 'הזן סכום חיובי, עד שתי ספרות אחרי הנקודה.',
      account: 'בחר חשבון.',
      toAccount: 'בחר חשבון יעד שונה מחשבון המקור.',
      note: 'תיקון דורש הערה.',
      direction: 'בחר כיוון.',
      date: 'בחר תאריך.',
      opening_balance_exists: 'לחשבון הזה כבר יש יתרת פתיחה. ערוך אותה במקום להוסיף חדשה.',
    },
  },

  accounts: {
    title: 'חשבונות',
    add: 'חשבון חדש',
    edit: 'עריכת חשבון',
    total: 'סה"כ',
    closed: 'חשבונות סגורים',
    empty: 'עוד אין חשבונות.',
    name: 'שם החשבון',
    namePlaceholder: 'עו"ש לאומי',
    kind: 'סוג',
    institution: 'בנק / גוף',
    noInstitution: 'ללא',
    openingBalance: 'יתרה היום',
    openingBalanceHint: 'הזן את היתרה כפי שהיא בבנק. במינוס? הוסף סימן מינוס.',
    openingDate: 'נכון לתאריך',
    overdraftLimit: 'מסגרת אשראי בעו"ש',
    overdraftRate: 'ריבית שנתית על המינוס (%)',
    visibleOnDashboard: 'להציג בדף הבית',
    closeAccount: 'סגירת חשבון',
    reopenAccount: 'פתיחה מחדש',
    deleteAccount: 'מחיקת חשבון',
    closeNotZero: 'אפשר לסגור חשבון רק כשהיתרה 0. העבר את היתרה או הוסף תיקון.',
    deleteHasTx: 'לחשבון יש תנועות, ולכן אי אפשר למחוק אותו. אפשר לסגור אותו.',
    deleteHasCards: 'יש כרטיסים שמחויבים מהחשבון הזה.',
    balance: 'יתרה',
    overdrawn: 'במינוס',
    availableWithOverdraft: 'זמין כולל מסגרת',
    overdraftAlert: (pct: string) => `ניצלת ${pct} מהמסגרת`,
    monthlyInterest: 'ריבית משוערת לחודש',
    incomeThisMonth: 'הכנסות החודש',
    expenseThisMonth: 'הוצאות החודש',
    balanceChart: 'יתרה ב-90 הימים האחרונים',
    transactions: 'תנועות',
    addTransaction: 'הוספת תנועה',
    kindFilterAll: 'הכול',
  },

  cards: {
    title: 'כרטיסים',
    add: 'כרטיס חדש',
    edit: 'עריכת כרטיס',
    name: 'שם הכרטיס',
    namePlaceholder: 'כאל ויזה זהב',
    issuer: 'חברת כרטיסים',
    last4: '4 ספרות אחרונות',
    last4Hint: 'רק 4 ספרות. מספר כרטיס מלא לא נשמר.',
    kind: 'סוג',
    credit: 'אשראי (חיוב נדחה)',
    debit: 'דביט (חיוב מיידי)',
    billingAccount: 'חשבון לחיוב',
    chargeDay: 'יום החיוב בחודש',
    calendarCycle: 'מחזור לפי חודש קלנדרי',
    calendarCycleHint: 'ברוב הכרטיסים: קניות של כל החודש מחויבות בחודש הבא. אם המחזור נסגר ביום אחר, כבה והזן אותו.',
    cutoffDay: 'יום סגירת המחזור',
    creditLimit: 'מסגרת אשראי',
    closeCard: 'סגירת כרטיס',
    reopenCard: 'הפעלה מחדש',
    deleteCard: 'מחיקת כרטיס',
    deleteHasTx: 'יש תנועות בכרטיס, ולכן אי אפשר למחוק אותו. אפשר לסגור אותו.',
    needAccount: 'כדי להוסיף כרטיס צריך קודם חשבון בנק לחיוב.',
    nextCharge: 'החיוב הקרוב',
    noCharge: 'אין חיוב פתוח',
    chargeOn: (d: string) => `ב-${d}`,
    available: 'מסגרת פנויה',
    utilization: 'ניצול מסגרת',
    openTotal: 'חיובים פתוחים',
    futureInstallments: 'תשלומים עתידיים',
    statements: 'חיובים',
    statementOf: (d: string) => `חיוב ${d}`,
    period: (a: string, b: string) => `${a} עד ${b}`,
    status: { open: 'פתוח', closed: 'נסגר, ממתין לחיוב', paid: 'שולם' },
    carried: 'זיכוי מחיוב קודם',
    installmentOf: (n: number, c: number) => `תשלום ${n} מתוך ${c}`,
    paymentMismatch: (paid: string, total: string) => `הבנק חויב ${paid}, אבל סכום החיוב עכשיו ${total}.`,
    alignPayment: 'עדכון החיוב לסכום',
    futureByMonth: 'תשלומים עתידיים לפי חודש',
    empty: 'אין עדיין חיובים בכרטיס.',
    debitNote: 'כרטיס דביט: כל עסקה יורדת מיד מחשבון הבנק, בלי חיוב חודשי.',
    addPurchase: 'הוספת עסקה',
  },

  installments: {
    toggle: 'בתשלומים?',
    count: 'מספר תשלומים',
    kind: 'סוג',
    installments: 'תשלומים',
    credit: 'קרדיט (עם ריבית)',
    interest: 'סך הריבית',
    interestHint: 'הסכום למעלה צריך לכלול את הריבית. היא מוצגת בנפרד.',
    recognition: 'בתקציב',
    upfront: 'הכול בחודש הקנייה',
    spread: 'לפי חודש חיוב',
    firstCharge: 'חיוב ראשון',
    preview: (first: string, rest: string, n: number) => (n > 1 ? `${first} ואחר כך ${n - 1} × ${rest}` : first),
    countError: 'בין 2 ל-60 תשלומים',
  },

  categories: {
    title: 'קטגוריות',
    add: 'קטגוריה חדשה',
    edit: 'עריכת קטגוריה',
    name: 'שם',
    type: 'סוג',
    typeExpense: 'הוצאה',
    typeIncome: 'הכנסה',
    parent: 'קטגוריית אב',
    noParent: 'ללא (ראשית)',
    context: 'שייך ל',
    includeInBudget: 'נכלל בתקציב',
    monthlyBudget: 'תקציב חודשי',
    expense: 'הוצאות',
    income: 'הכנסות',
    business: 'עסק',
    errors: {
      parent_too_deep: 'אפשר רק רמה אחת של תת-קטגוריות.',
      parent_type: 'תת-קטגוריה חייבת להיות מאותו סוג כמו האב.',
      has_children: 'לקטגוריה הזו יש תת-קטגוריות, ולכן היא לא יכולה להיות תת-קטגוריה.',
      parent_self: 'קטגוריה לא יכולה להיות האב של עצמה.',
    },
    deleteHint: 'תנועות קיימות ישמרו את הקטגוריה בהיסטוריה.',
  },

  plan: {
    title: 'תכנון',
    budget: 'תקציב',
    recurring: 'חשבונות קבועים ומנויים',
    wishList: 'Wish List',
    forecast: 'תחזית יתרה',
  },

  more: {
    title: 'עוד',
    accounts: 'חשבונות וכרטיסים',
    debts: 'הלוואות וחובות',
    checks: "צ'קים",
    investments: 'השקעות',
    pension: 'פנסיה וגמל',
    salary: 'שכר',
    business: 'עסק',
    tax: 'הגדרות מס',
    reports: 'דוחות',
    import: 'ייבוא',
    settings: 'הגדרות',
  },

  pin: {
    title: 'קוד נעילה',
    enter: 'הזן קוד',
    wrong: 'קוד שגוי',
    set: 'הגדרת קוד',
    change: 'שינוי קוד',
    remove: 'הסרת קוד',
    newPin: 'קוד חדש (4–6 ספרות)',
    confirmPin: 'אימות הקוד',
    mismatch: 'הקודים לא תואמים',
    invalid: 'הקוד צריך להיות 4 עד 6 ספרות',
    on: 'האפליקציה ננעלת אחרי 5 דקות ברקע',
    off: 'אין קוד',
    hint: 'הגנה מפני מבט מזדמן, לא הצפנה של הנתונים. אם תשכח את הקוד, תצטרך לשחזר מגיבוי.',
    delete: 'מחיקה',
  },

  csv: {
    title: 'ייצוא CSV לרואה חשבון',
    from: 'מתאריך',
    to: 'עד תאריך',
    context: 'תנועות',
    export: 'ייצוא CSV',
    empty: 'אין תנועות בטווח הזה.',
    done: (n: number) => `יוצאו ${n.toLocaleString('he-IL')} תנועות`,
    headers: ['תאריך', 'סוג', 'סכום', 'חשבון', 'כרטיס', 'לחשבון', 'קטגוריה', 'בית עסק', 'תיאור', 'הערה', 'תגיות', 'אישי/עסקי', 'סטטוס', 'מע"מ', 'נטו'],
  },

  settings: {
    title: 'הגדרות',
    appearance: 'תצוגה',
    theme: 'תמה',
    themeSystem: 'לפי המכשיר',
    themeLight: 'בהירה',
    themeDark: 'כהה',
    hideAgorot: 'הסתרת אגורות',
    hideAgorotHint: 'סכומים יוצגו בשקלים שלמים',
    data: 'נתונים',
    categories: 'קטגוריות',
    security: 'אבטחה',

    backup: 'גיבוי ושחזור',
    lastBackup: 'גיבוי אחרון',
    backupPassword: 'סיסמה להצפנה (לא חובה)',
    backupPasswordHint: 'בלי סיסמה הקובץ לא מוצפן. אם תשכח את הסיסמה, אי אפשר לשחזר.',
    backupPasswordConfirm: 'אימות סיסמה',
    passwordMismatch: 'הסיסמאות לא תואמות',
    exportBackup: 'ייצוא גיבוי',
    exporting: 'מייצא…',
    exportDone: 'קובץ הגיבוי נשמר',
    restore: 'שחזור מקובץ',
    restoreHint: 'השחזור מחליף את כל הנתונים במכשיר בנתונים מהקובץ.',
    restorePasswordPrompt: 'הקובץ מוצפן. הזן את הסיסמה:',
    restoreCheck: 'בדיקת הקובץ',
    restoreSummary: (date: string, rows: number) => `גיבוי מ-${date}, ${rows.toLocaleString('he-IL')} רשומות.`,
    restoreConfirm1Title: 'להחליף את כל הנתונים?',
    restoreConfirm1Body: 'כל מה ששמור עכשיו במכשיר יימחק ויוחלף בנתונים מהקובץ.',
    restoreConfirm2Title: 'אישור אחרון',
    restoreConfirm2Body: 'אי אפשר לבטל את הפעולה הזו. כדאי לייצא גיבוי של המצב הנוכחי לפני כן.',
    restoreYes: 'כן, להחליף',
    restoreFinal: 'שחזר עכשיו',
    restoreDone: 'השחזור הושלם',
    errors: {
      not_a_backup: 'הקובץ הזה לא גיבוי של Finance OS.',
      newer_version: 'הגיבוי נוצר בגרסה חדשה יותר של האפליקציה. עדכן את האפליקציה ונסה שוב.',
      needs_password: 'הקובץ מוצפן. הזן סיסמה.',
      invalid_data: 'הקובץ פגום או ערוך, ולכן לא שוחזר. הנתונים הקיימים לא השתנו.',
      wrong_password: 'סיסמה שגויה, או שהקובץ פגום.',
      generic: 'משהו השתבש. הנתונים הקיימים לא השתנו.',
    },

    storage: 'אחסון',
    storagePersisted: 'האחסון מוגן מפני מחיקה אוטומטית',
    storageNotPersisted: 'האחסון לא מוגן. התקן למסך הבית.',
    installed: 'מותקן כאפליקציה',
    notInstalled: 'פתוח בדפדפן',

    about: 'אודות',
    privacy: 'כל הנתונים נשמרים במכשיר הזה בלבד. שום נתון לא נשלח לשרת.',
    disclaimer: 'החישובים הם כלי תכנון ואינם ייעוץ מס או ייעוץ פיננסי.',
    version: 'גרסה',
  },
} as const;
