/** All user-facing text (CLAUDE.md: one translation file). */
export const he = {
  appName: 'Finance OS',

  nav: {
    home: 'בית',
    transactions: 'תנועות',
    add: 'הוספה',
    plan: 'תכנון',
    more: 'עוד',
    mainLabel: 'ניווט ראשי',
  },

  common: {
    back: 'חזרה',
    close: 'סגירה',
    cancel: 'ביטול',
    continue: 'המשך',
    comingInStage: (n: number) => `בשלב ${n}`,
    comingSoonTitle: 'המסך הזה עוד בבנייה',
    comingSoonBody: (n: number) => `הוא ייבנה בשלב ${n} לפי תוכנית העבודה.`,
    never: 'אף פעם',
  },

  home: {
    netWorth: 'שווי נטו',
    netWorthPending: 'יחושב אחרי שתוסיף חשבונות',
    liquid: 'יתרה נזילה',
    budget: 'תקציב החודש',
    cashflow: 'תזרים החודש',
    debts: 'חובות',
    emptyTitle: 'מתחילים כאן',
    emptyBody: 'בשלב הבא נוסיף חשבונות, תנועות ויתרות. בינתיים אפשר לבחור תמה ולבדוק גיבוי בהגדרות.',
    openSettings: 'להגדרות',
  },

  banners: {
    installTitle: 'התקנה למסך הבית',
    installBodyIos: 'בספארי: כפתור השיתוף ← "הוסף למסך הבית". כך הנתונים שמורים טוב יותר והאפליקציה עובדת בלי רשת.',
    installBodyOther: 'התקן את האפליקציה מתפריט הדפדפן כדי שהנתונים יישמרו טוב יותר.',
    backupTitle: 'הגיע הזמן לגיבוי',
    backupBody: (days: string) => `הגיבוי האחרון: ${days}. הנתונים שמורים רק במכשיר הזה.`,
    backupNever: 'עוד לא גיבית',
    backupAction: 'לגיבוי',
    storageTitle: 'האחסון לא מוגן',
    storageBody: 'הדפדפן עלול למחוק נתונים אם האפליקציה לא תיפתח זמן רב. התקן למסך הבית וגבה באופן קבוע.',
    dismiss: 'סגירה',
  },

  quickAdd: {
    title: 'הוספה מהירה',
    expense: 'הוצאה',
    income: 'הכנסה',
    transfer: 'העברה',
    note: 'הוספת תנועות תיפתח בשלב 1.',
  },

  transactions: {
    title: 'תנועות',
    emptyTitle: 'אין עדיין תנועות',
    emptyBody: 'רשימת התנועות, חיפוש וסינון ייבנו בשלב 1.',
  },

  plan: {
    title: 'תכנון',
    budget: 'תקציב',
    recurring: 'חשבונות קבועים ומנויים',
    wishList: 'Wish List',
    forecast: 'תחזית יתרה',
  },

  more: {
    title: 'עוד',
    accounts: 'חשבונות וכרטיסים',
    debts: 'הלוואות וחובות',
    checks: "צ'קים",
    investments: 'השקעות',
    pension: 'פנסיה וגמל',
    salary: 'שכר',
    business: 'עסק',
    tax: 'הגדרות מס',
    reports: 'דוחות',
    import: 'ייבוא',
    settings: 'הגדרות',
  },

  settings: {
    title: 'הגדרות',
    appearance: 'תצוגה',
    theme: 'תמה',
    themeSystem: 'לפי המכשיר',
    themeLight: 'בהירה',
    themeDark: 'כהה',
    hideAgorot: 'הסתרת אגורות',
    hideAgorotHint: 'סכומים יוצגו בשקלים שלמים',

    backup: 'גיבוי ושחזור',
    lastBackup: 'גיבוי אחרון',
    backupPassword: 'סיסמה להצפנה (לא חובה)',
    backupPasswordHint: 'בלי סיסמה הקובץ לא מוצפן. אם תשכח את הסיסמה, אי אפשר לשחזר.',
    backupPasswordConfirm: 'אימות סיסמה',
    passwordMismatch: 'הסיסמאות לא תואמות',
    exportBackup: 'ייצוא גיבוי',
    exporting: 'מייצא…',
    exportDone: 'קובץ הגיבוי נשמר',
    restore: 'שחזור מקובץ',
    restoreHint: 'השחזור מחליף את כל הנתונים במכשיר בנתונים מהקובץ.',
    restorePasswordPrompt: 'הקובץ מוצפן. הזן את הסיסמה:',
    restoreCheck: 'בדיקת הקובץ',
    restoreSummary: (date: string, rows: number) => `גיבוי מ-${date}, ${rows.toLocaleString('he-IL')} רשומות.`,
    restoreConfirm1Title: 'להחליף את כל הנתונים?',
    restoreConfirm1Body: 'כל מה ששמור עכשיו במכשיר יימחק ויוחלף בנתונים מהקובץ.',
    restoreConfirm2Title: 'אישור אחרון',
    restoreConfirm2Body: 'אי אפשר לבטל את הפעולה הזו. כדאי לייצא גיבוי של המצב הנוכחי לפני כן.',
    restoreYes: 'כן, להחליף',
    restoreFinal: 'שחזר עכשיו',
    restoreDone: 'השחזור הושלם',
    errors: {
      not_a_backup: 'הקובץ הזה לא גיבוי של Finance OS.',
      newer_version: 'הגיבוי נוצר בגרסה חדשה יותר של האפליקציה. עדכן את האפליקציה ונסה שוב.',
      needs_password: 'הקובץ מוצפן. הזן סיסמה.',
      invalid_data: 'הקובץ פגום או ערוך, ולכן לא שוחזר. הנתונים הקיימים לא השתנו.',
      wrong_password: 'סיסמה שגויה, או שהקובץ פגום.',
      generic: 'משהו השתבש. הנתונים הקיימים לא השתנו.',
    },

    storage: 'אחסון',
    storagePersisted: 'האחסון מוגן מפני מחיקה אוטומטית',
    storageNotPersisted: 'האחסון לא מוגן. התקן למסך הבית.',
    installed: 'מותקן כאפליקציה',
    notInstalled: 'פתוח בדפדפן',

    about: 'אודות',
    privacy: 'כל הנתונים נשמרים במכשיר הזה בלבד. שום נתון לא נשלח לשרת.',
    disclaimer: 'החישובים הם כלי תכנון ואינם ייעוץ מס או ייעוץ פיננסי.',
    version: 'גרסה',
  },
} as const;
